version: '3'
services:
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    working_dir: /usr/src/app
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/usr/src/app